updating codemagic.yaml

diff --git a/codemagic.yaml b/codemagic.yaml
--- a/codemagic.yaml
+++ b/codemagic.yaml
@@ -4,6 +4,9 @@ workflows:
   development:
     name: build, test & publish Dev version, Android & iOS
     instance_type: mac_pro
+    max_build_duration: 30
+    integrations:
+      app_store_connect: codemagic
     triggering:
       events:
         - push
@@ -14,9 +17,18 @@ workflows:
       tag_patterns:
         - pattern: build v+([0-9]).+([0-9]).+([0-9])
       cancel_previous_builds: true
+    vars:
+      GOOGLE_SERVICES_iOS_PLIST: PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0iVVRGLTgiPz4KPCFET0NUWVBFIHBsaXN0IFBVQkxJQyAiLS8vQXBwbGUvL0RURCBQTElTVCAxLjAvL0VOIiAiaHR0cDovL3d3dy5hcHBsZS5jb20vRFREcy9Qcm9wZXJ0eUxpc3QtMS4wLmR0ZCI+CjxwbGlzdCB2ZXJzaW9uPSIxLjAiPgo8ZGljdD4KCTxrZXk+QVBJX0tFWTwva2V5PgoJPHN0cmluZz5BSXphU3lEcDFBZnBvR0dvQ1g2UF95YlEySTdham42YVBCTXIzc1U8L3N0cmluZz4KCTxrZXk+R0NNX1NFTkRFUl9JRDwva2V5PgoJPHN0cmluZz43NzE1Mzg5Mzc3OTQ8L3N0cmluZz4KCTxrZXk+UExJU1RfVkVSU0lPTjwva2V5PgoJPHN0cmluZz4xPC9zdHJpbmc+Cgk8a2V5PkJVTkRMRV9JRDwva2V5PgoJPHN0cmluZz5jb20uZXhhbXBsZS5jb2RlbWFnaWNGbHV0dGVyQ2ljZDwvc3RyaW5nPgoJPGtleT5QUk9KRUNUX0lEPC9rZXk+Cgk8c3RyaW5nPnRlc3RhcHAtOGUwYWI8L3N0cmluZz4KCTxrZXk+U1RPUkFHRV9CVUNLRVQ8L2tleT4KCTxzdHJpbmc+dGVzdGFwcC04ZTBhYi5hcHBzcG90LmNvbTwvc3RyaW5nPgoJPGtleT5JU19BRFNfRU5BQkxFRDwva2V5PgoJPGZhbHNlPjwvZmFsc2U+Cgk8a2V5PklTX0FOQUxZVElDU19FTkFCTEVEPC9rZXk+Cgk8ZmFsc2U+PC9mYWxzZT4KCTxrZXk+SVNfQVBQSU5WSVRFX0VOQUJMRUQ8L2tleT4KCTx0cnVlPjwvdHJ1ZT4KCTxrZXk+SVNfR0NNX0VOQUJMRUQ8L2tleT4KCTx0cnVlPjwvdHJ1ZT4KCTxrZXk+SVNfU0lHTklOX0VOQUJMRUQ8L2tleT4KCTx0cnVlPjwvdHJ1ZT4KCTxrZXk+R09PR0xFX0FQUF9JRDwva2V5PgoJPHN0cmluZz4xOjc3MTUzODkzNzc5NDppb3M6MTJiNjdiYTgzNzBlYzYzM2MyNTg1Yjwvc3RyaW5nPgo8L2RpY3Q+CjwvcGxpc3Q+
+      GOOGLE_SERVICES_ANDROID_JSON: ewogICJwcm9qZWN0X2luZm8iOiB7CiAgICAicHJvamVjdF9udW1iZXIiOiAiNzcxNTM4OTM3Nzk0IiwKICAgICJwcm9qZWN0X2lkIjogInRlc3RhcHAtOGUwYWIiLAogICAgInN0b3JhZ2VfYnVja2V0IjogInRlc3RhcHAtOGUwYWIuYXBwc3BvdC5jb20iCiAgfSwKICAiY2xpZW50IjogWwogICAgewogICAgICAiY2xpZW50X2luZm8iOiB7CiAgICAgICAgIm1vYmlsZXNka19hcHBfaWQiOiAiMTo3NzE1Mzg5Mzc3OTQ6YW5kcm9pZDpiMmZkNmM4NWUzZjhjMGNiYzI1ODViIiwKICAgICAgICAiYW5kcm9pZF9jbGllbnRfaW5mbyI6IHsKICAgICAgICAgICJwYWNrYWdlX25hbWUiOiAiY29tLmV4YW1wbGUuY29kZW1hZ2ljRmx1dHRlckNpY2QiCiAgICAgICAgfQogICAgICB9LAogICAgICAib2F1dGhfY2xpZW50IjogW10sCiAgICAgICJhcGlfa2V5IjogWwogICAgICAgIHsKICAgICAgICAgICJjdXJyZW50X2tleSI6ICJBSXphU3lDV1RnR2VheGdYYkZEY09GaFhfM01uRnp6X3ZrU3pTZHciCiAgICAgICAgfQogICAgICBdLAogICAgICAic2VydmljZXMiOiB7CiAgICAgICAgImFwcGludml0ZV9zZXJ2aWNlIjogewogICAgICAgICAgIm90aGVyX3BsYXRmb3JtX29hdXRoX2NsaWVudCI6IFtdCiAgICAgICAgfQogICAgICB9CiAgICB9CiAgXSwKICAiY29uZmlndXJhdGlvbl92ZXJzaW9uIjogIjEiCn0=
+      APP_STORE_APP_ID: 6445854107
+      APP_NAME: "Svarupa"
+      PACKAGE_NAME: "com.app.svarupa"
+      GOOGLE_PLAY_TRACK: "alpha"
     environment:
       flutter: 3.13.7
       java: 1.8
+      cocoapods: default
+      xcode: latest
     cache:
       cache_paths:
         - $FLUTTER_ROOT/.pub-cache
@@ -24,10 +36,46 @@ workflows:
 
 
     scripts:
-      - ...
+      - name: Set up local.properties
+        script: echo "flutter.sdk=$HOME/programs/flutter" > "$CM_BUILD_DIR/android/local.properties" # Set Flutter SDK path for Android project
 
+      - name: Get Flutter packages  # run gets flutter packages of project
+        script: flutter packages pub get
 
+#      - name: Flutter analyze
+#        script: flutter analyze
+#      - name: Flutter unit tests
+#        script: flutter test
+#        ignore_failure: true
 
+      - name: Build Android App Bundle in Flutter
+        script: flutter build aab --release build-name=1.0.$BUILD_NUMBER --build-number=$BUILD_NUMBER
+
+      - name: Set up code signing settings on Xcode project
+        script: |
+          xcode-project use-profiles
+      - name: Install pods
+        script: |
+          find . -name "Podfile" -execdir pod install \;
+      - name: Flutter build ipa and automatic versioning
+        script: |
+          flutter build ipa --release build-name=1.0.$BUILD_NUMBER --build-number=$BUILD_NUMBER
+    artifacts:
+      - build/**/outputs/bundle/**/*.aab
+      - build/**/outputs/**/mapping.txt
+    publishing:
+      email:
+        recipients:
+          - sshivam@citridot.com
+        notify:
+          success: true
+          failure: false
+      app_store_connect:
+        auth: integration
+        submit_to_testflight: true
+        beta_groups: # Specify the names of beta tester groups that will get access to the build once it has passed beta review.
+          - group name 1
+        submit_to_app_store: false
 
   # Production Workflow
   production:
@@ -45,6 +93,35 @@ workflows:
         - $HOME/Library/Caches/CocoaPods
 
     scripts:
-      - ...
+      - name: Add Provisioning profiles
+        script: |
+          set -e # exit on first failed command
 
+          PROFILES_HOME="$HOME/Library/MobileDevice/Provisioning Profiles"
+          mkdir -p "$PROFILES_HOME"
+          echo ${PROVISIONING_PROFILE?} | base64 --decode > "$PROFILES_HOME/$(uuidgen).mobileprovision"
+      - name: Add signing certificate
+        script: |
+          set -e # exit on first failed command
+
+          echo ${CERTIFICATE?} | base64 --decode > /tmp/certificate.p12
+          keychain initialize
+          keychain add-certificates \
+              --certificate /tmp/certificate.p12 \
+              --certificate-password ${CERTIFICATE_PASSWORD?}
+      - name: Increment build number
+        script: agvtool new-version -all $BUILD_NUMBER
+      - name: Set up code signing settings on Xcode project
+        script: xcode-project use-profiles
+      - name: Build ipa for distribution
+        script: xcode-project build-ipa \
+          --workspace "${XCODE_WORKSPACE?}" \
+          --scheme "${XCODE_SCHEME?}"
+    artifacts:
+      - build/ios/ipa/*.ipa
+    publishing:
+      google_play:
+        credentials: $GCLOUD_SERVICE_ACCOUNT_CREDENTIALS
+        track: $GOOGLE_PLAY_TRACK
+        submit_as_draft: true
 
